### ISSUE TITLE
[Workflows]

### ISSUE THREAD

**Issue by Zsupi** [BME-MIT-IET/iet-hf-2022-aranyfacan#11]
# Tasks:

- [ ] Create a build.yml
- [ ] Add 2 jobs
     - [ ] from dotnet.yml
     - [ ] from current build.yml
