### ISSUE TITLE
[Documentation]

### ISSUE THREAD

**Issue by Zsupi** [BME-MIT-IET/iet-hf-2022-aranyfacan#14]
# Tasks:

- [x] [Documentation](https://github.com/BME-MIT-IET/iet-hf-2022-aranyfacan/tree/main/doc/product_bdd.md) for BDD tests 
- [x] [Documentation](https://github.com/BME-MIT-IET/iet-hf-2022-aranyfacan/tree/main/doc/technology_deployment.md) for Docker
- [x] [Documentation](https://github.com/BME-MIT-IET/iet-hf-2022-aranyfacan/tree/main/doc/sonar_cloud.md) SonarCloud
- [x] [Documentation](https://github.com/BME-MIT-IET/iet-hf-2022-aranyfacan/tree/main/doc/technology_nonfunctional.md) Non-functional tests

**Comment by varjanos** [comment]
All docs done! Find them in [doc](https://github.com/BME-MIT-IET/iet-hf-2022-aranyfacan/tree/main/doc) folder.
