### ISSUE TITLE
[BDD tests with Specflow]

### ISSUE THREAD

**Issue by JanosVargaBME** [BME-MIT-IET/iet-hf-2022-aranyfacan#6]
Create BDD tests for the project with Specflow!

**Tasks:**

- [x] RDFGraph tests @JanosVargaBME 
- [x] RDFCollection tests @JanosVargaBME 
- [x] RDFQuery tests @JanosVargaBME 
- [x] [Documentation](https://github.com/BME-MIT-IET/iet-hf-2022-aranyfacan/blob/product_bdd/doc/product_bdd.md)
- [x] Needs review before merge! @Zsupi @adamooo1

**Comment by JanosVargaBME** [comment]
All tasks done, tests working like a fine wine! 🍷 :D
